nmea_serial_driver:
  ros__parameters:
    port: "/dev/tty.usbserial"
    baud: 115200
    frame_id: "gps"
    time_ref_source: "gps"
    ntrip_host: "rtk.geodnet.com"
    ntrip_port: 2101
    ntrip_mountpoint: "AUTO"
    ntrip_username: "hyfix" #replace with NTRIP username
    ntrip_password: "hyfix" #replace with NTRIP password